### ISSUE TITLE
Question: is Amphetamine Enhancer a thing?

### ISSUE THREAD

**Issue by mcorossigo** [x74353/Amphetamine-Enhancer#1]
Hello @x74353 

Fist of all, thank you so much for Amphetamine. It's just perfect!

I'm coming from https://iffy.freshdesk.com/support/solutions/articles/48000966632-setting-up-amphetamine-enhancer and.. well the repo is empty with no releases attached.

So, am I missing something?

Thanks

**Comment by mcorossigo** [comment]
Nevermind, I see from

> When Amphetamine Enhancer become available, it will be available on Github.

and

> Amphetamine Enhancer is a forthcoming application that expands several core Amphetamine features.

that it's not been yet released.

**Comment by x74353** [comment]
Thanks for the kind words about Amphetamine. The Enhancer isn't quite ready yet. Fingers-crossed Apple will notarize it when it's finally ready! I'm in the final stretch (I hope).
<img width="812" alt="Screen Shot 2019-11-14 at 6 54 03 PM" src="https://user-images.githubusercontent.com/1432223/68905738-36e3ee80-0710-11ea-8b13-9673280cd702.png">
