### ISSUE TITLE
Lock user account but don't sleep

### ISSUE THREAD

**Issue by nekename** [x74353/Amphetamine-Enhancer#11]
In Amphetamine, please could you add support for a setting that when you shut the lid of a MacBook, it doesn't go to sleep, but it shows the lock screen (just password entry, not complete logout)?

I would like to be able to keep my data secure without sleeping my Mac. I could just Control-Command-Q before shutting my screen, but I'm lazy.

I don't know if macOS lets other applications lock the screen, but if it does, this would be extremely helpful. I also don't know if this is for Amphetamine Enhancer or just Amphetamine, but I couldn't find anywhere else to post this.

**Comment by DUOLabs333** [comment]
I'm looking for this too.

**Comment by nekename** [comment]
What I did is just press the shortcut and I got used to it, it's a reflex now.

**Comment by DUOLabs333** [comment]
I was able to get it done with Fermata and 
```
#!/opt/local/bin/bash

cd ~/scripts 
while true
do
	if [[ $(ioreg -r -k AppleClamshellState | grep '"AppleClamshellState"' | cut -f2 -d"=") = ' Yes' ]]; then
		./lockscreen
		sleep 1
	fi
done
```

`./lockscreen` comes from [here](https://stackoverflow.com/a/26492632/12039011)

**Comment by nekename** [comment]
Nice!
