### ISSUE TITLE
Amphetamine Enhancer dmg file doesn't download. 

### ISSUE THREAD

**Issue by viraj89** [x74353/Amphetamine-Enhancer#31]
Hi @x74353  - for some reason, the Amphetamine Enhancer dmg file doesn't download. 
The raw.githubusercontent.com site looks unreachable. 
Can you please check the raw version and update the file please so that it downloads? Thanks. 
![Screenshot](https://user-images.githubusercontent.com/9387490/207388206-9156c77b-5472-4a4b-929f-08ec7f93b9b5.png)

**Comment by karenetheridge** [comment]
That's a networking problem that you'll need to solve on your end.

**Comment by AleesJaved** [comment]
Got the same problem won't download

**Comment by viraj89** [comment]
@karenetheridge Are you able to download the dmg file? If so, could you upload it to a google drive public folder and share the link, please? 

@AleesJaved - I tried again, but no luck yet. 

@x74353 - Please intervene and help us. TIA.

**Comment by karenetheridge** [comment]
It's https://github.com/x74353/Amphetamine-Enhancer/raw/master/Releases/Current/Amphetamine%20Enhancer.dmg, which is linked from the main github page.

**Comment by viraj89** [comment]
Okay. Here's something I tried after your comment this time. Used Nord VPN and connected to the US region and voila, it downloaded the DMG file.
@AleesJaved - I think you should try this too, and hope it works. If it works, do confirm, so that we can close this issue. 
@karenetheridge - Can't thank you enough, I appreciate it. However, wondering why GitHub is restricting non-US users to download this file.

**Comment by karenetheridge** [comment]
> However, wondering why GitHub is restricting non-US users to download this file.

They're not. I'm not in the US either.  
Check with your ISP.

**Comment by viraj89** [comment]
Anyway, I am closing this issue. Thank you again.
